on: 
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
name: Build & Release
jobs:
  build_latex:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
        - name: Compile LaTeX document
          uses: xu-cheng/latex-action@v2
          with:
            root_file: main.tex
        - name: Archive pdf
          uses: actions/upload-artifact@v2
          with:
            name: thesis
            path: main.pdf
              
  release:
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
      - name: Download PDF artifact
        uses: actions/download-artifact@v2
        with:
          name: thesis
      - name: Upload release artifacts
        uses: ncipollo/release-action@v1
        with:
          tag: "latest"
          artifacts: "main.pdf"
          name: Bachelor Thesis
          makeLatest: true
