on: 
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
name: Build & Release
jobs:
  build_latex:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
        - name: Compile LaTeX document
          uses: xu-cheng/latex-action@v2
          with:
            root_file: main.tex       
  release:
      runs-on: ubuntu-latest
      needs: [build_latex]
      steps:
        - name: checkout Repository
          uses: actions/checkout@v3
        - name: Create release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            automatic_release_tag: "latest"
            prerelease: false
            title: "Bachelor thesis"
            files: |
              main.pdf
